### ISSUE TITLE
Enable Packet CLI flags

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#5]
## Expected Behaviour

We should be able to create/delete with the Packet.com provisioner

## Current Behaviour

The code is present, but it's not hooked up to any CLI flags yet

## Possible Solution

Copy the approach for DO / Scaleway. Have fun

Update these two methods:

https://github.com/inlets/inletsctl/blob/3b53f1dca10c1597d4c14a50bd305b6306757826/cmd/create.go#L207

https://github.com/inlets/inletsctl/blob/3b53f1dca10c1597d4c14a50bd305b6306757826/cmd/create.go#L193

Then check the CLI flags are all being brought in as needed:

https://github.com/inlets/inletsctl/blob/3b53f1dca10c1597d4c14a50bd305b6306757826/cmd/create.go#L21

Perform the above for create.go and delete.go

The vendored package "provision" already contains code for Packet - https://github.com/inlets/inletsctl/blob/3b53f1dca10c1597d4c14a50bd305b6306757826/vendor/github.com/inlets/inlets-operator/pkg/provision/packet.go

**Comment by u5surf** [comment]
@alexellis Hi, I'll try this issue.

**Comment by alexellis** [comment]
Thank you

**Comment by vielmetti** [comment]
A tiny note here - if you provision with packet and omit the `project-id` flag you end up with an unexpected 404 error instead of a working server

https://github.com/inlets/inletsctl/blob/master/cmd/create.go#L154

looks like where you'd need to insert some added code to test that flag for GCE and Packet. Otherwise I can confirm that it works nicely.

**Comment by alexellis** [comment]
Sounds good, thank you for letting us know. I'd like someone to send a PR for it.
